# Generated by Django 3.0 on 2019-12-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
