# Generated by Django 3.1.4 on 2020-12-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poruke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='num_views',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='num_views',
        ),
    ]
