
# Generated by Django 3.1.4 on 2020-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poruke', '0002_auto_20201228_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
