# Generated by Django 3.1.4 on 2020-12-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poruke', '0003_auto_20201228_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
